### ISSUE TITLE
the directory /usr/lcoal does not exist

### ISSUE THREAD

**Issue by devil67** [samhaxr/recox#1]
Like i undertand you but not understand 
the command mv on mv recox.sh /usr/lcoal/bin/recox  does not exist 

maybe you meant to create a folder  with this comand mv recox.sh /usr/local/bin/recox
Can you explain it what can i do thanks

**Comment by samhaxr** [comment]
Thank you for reporting this issue. I have fixed it in the repository. its local not lcoal /usr/local/bin.
