### ISSUE TITLE
APIs missing

### ISSUE THREAD

**Issue by amiranda0213** [samhaxr/recox#4]
Hi when i start recox i am getting the api keys are missing. exiting program
![image](https://user-images.githubusercontent.com/66804171/88105949-50c0b580-cb6a-11ea-8502-27b92579e1d6.png)

How can i get the apis that are missing?

**Comment by rzkytmgr** [comment]
You must add your shodan and virustotal API in `recox.sh` file
Read this Closed [Issue #2](https://github.com/samhaxr/recox/issues/2)
