### ISSUE TITLE
[!] Please check your internet connection and then try again...

### ISSUE THREAD

**Issue by jitinyaduvanshi** [samhaxr/recox#5]
![Screenshot_20200812-110230](https://user-images.githubusercontent.com/69568631/89978532-42435680-dc5d-11ea-95a3-f8868bdb0ee8.png)

**Comment by samhaxr** [comment]
RecoX is designed and tested on Mac OSX, Kali Linux, Parrot Linux. You can still use it on Ubuntu and other distros, but you have to install a few libraries manually. You can try it on termux by removing **connectivity** function from line number 557.

From
> 557 - validate ${domain};connectivity;web_infoga ${domain}

To
> 557 validate ${domain};web_infoga ${domain}
