### ISSUE TITLE
dns python required for takeovers

### ISSUE THREAD

**Issue by Rajkumar-427** [samhaxr/recox#6]
how to attach dnspython to recox , as it was asking dnspython to display the takeovers

**Comment by samhaxr** [comment]
Install the dnspython library with “pip install dnspython”
Further detail can be found on https://pypi.org/project/dnspython/

**Comment by Rajkumar-427** [comment]
hi sir ,
i had already installed and it is saying requirement already satisfied but
for takeovers in  recox its asking again and again for dnspython

**Comment by samhaxr** [comment]
Which linux distro you are using?

**Comment by Rajkumar-427** [comment]
kali

**Comment by Rajkumar-427** [comment]
sir can i have your whatsapp it will be easy for conversation
